front/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :restaurants do
    resources :dishes
  end
  resources :customers

  get '/login/:customer_id', to: 'sessions#login', as: 'logmein'
  get '/logout', to: 'sessions#logout', as: 'logmeout'

  get '/orders/surprise', to: 'orders#surprise', as: 'surprise'
  get '/orders/:dish_id', to: 'orders#create', as: 'order'
  get '/orders', to: 'orders#index', as: 'orders_index'

  root to: 'sessions#index'
end

front/app/models/base_resource.rb
class BaseResource < JsonApiClient::Resource
  self.site = ENV.fetch('API_URL', 'http://localhost:3000')
end

front/app/models/customer.rb
class Customer < BaseResource
  property :first_name, type: :string
  property :last_name, type: :string
  property :address, type: :string
  property :email, type: :string

  has_many :orders
end

front/app/models/dish.rb
class Dish < BaseResource
  belongs_to :restaurant
end

front/app/models/item.rb
class Item < BaseResource
  property :quantity

  belongs_to :order
  belongs_to :dish
end

front/app/models/order.rb
class Order < BaseResource
  property :deliver_late

  belongs_to :customer
  has_many :items
end

front/app/models/restaurant.rb
class Restaurant < BaseResource
  has_many :dishes
end

front/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_customer
    if session[:customer_id]
      Customer.find(session[:customer_id]).first
    else
      nil
    end
  end

  def session_present?
    session[:customer_id]
  end
end

front/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  def create
    @customer = Customer.create(customer_params)

    if @customer.persisted?
      redirect_to @customer, notice: 'Customer was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /customers/1
  def update
    if @customer.update(customer_params)
      redirect_to @customer, notice: 'Customer was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /customers/1
  def destroy
    @customer.destroy
    redirect_to customers_url, notice: 'Customer was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit!
    end
end

front/app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :set_dish, only: [:show, :edit, :update, :destroy]

  # GET /dishes
  # GET /dishes.json
  def index
    @restaurant = Restaurant.find(restaurant_id)
    @dishes = Dish.where(restaurant_id: restaurant_id).all
  end

  # GET /dishes/1
  # GET /dishes/1.json
  def show
  end

  # GET /dishes/new
  def new
    @dish = Dish.new
  end

  # GET /dishes/1/edit
  def edit
  end

  # POST /dishes
  # POST /dishes.json
  def create
    @dish = Dish.create(dish_params.merge(restaurant_id: restaurant_id))

    if @dish.valid?
      redirect_to restaurant_dishes_path, notice: 'Dish was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /dishes/1
  # PATCH/PUT /dishes/1.json
  def update
    if @dish.update(dish_params)
      redirect_to @dish, notice: 'Dish was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /dishes/1
  def destroy
    @dish.destroy
    redirect_to dishes_url, notice: 'Dish was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dish
      @restaurant = Restaurant.find(restaurant_id).first
      @dish = Dish.where(restaurant_id: restaurant_id).find(dish_id).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dish_params
      params.require(:dish).permit!
    end

    def restaurant_id
      params[:restaurant_id]
    end

    def dish_id
      params[:id]
    end
end

front/app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders = Order.where(customer_id: customer_id).all
  end

  def create
    customer = current_customer

    if customer
      item  = Item.new(quantity: 1, dish_id: dish_id)
      order = Order.create(customer_id: customer.id,
                           deliver_late: DateTime.now,
                           items: [ JSON.parse(item.to_json) ])

      if order.persisted?
        flash[:success] = 'Your Order was registered!'
      else
        flash[:error] = 'Sorry, something went wrong!'
      end
      redirect_to root_path
    else
      flash[:info] = 'You are not logged'
      redirect_to customers_path
    end
  end

  def surprise
    customer = current_customer
    if customer
      uri = URI("#{endpoint}/customers/#{customer.id}/orders/surprise")

      result = Net::HTTP.post_form(uri, q: 'surprise')
      if result.code == '201'
        flash[:success] = 'Your surprise was sent. See the result in your email'
      else
        flash[:error] = 'Something went wrong!'
      end
      redirect_to root_path
    else
      flash[:info] = 'You are not logged'
      redirect_to customers_path
    end
  end

  private

  def customer_id
    session[:customer_id]
  end

  def endpoint
    ENV.fetch('API_URL', 'http://localhost:3000')
  end

  def order_params
    params.permit(:dish_id)
  end

  def dish_id
    order_params[:dish_id]
  end
end

front/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /restaurants/1
  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /restaurants/1
  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit!
    end
end

front/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index
    render :index
  end

  def login
    customer = Customer.find(customer_id).first
    if customer
      session[:customer_id] = customer.id
      redirect_to restaurants_path
    else
      flash.now[:danger] = 'Invalid Customer'
      redirect_to customers_path
    end
  end

  def logout
    session[:customer_id] = nil
    redirect_to customers_path
  end

  private

  def customer_id
    params[:customer_id]
  end

end

front/app/helpers/application_helper.rb
module ApplicationHelper
  def current_customer
    if session[:customer_id]
      Customer.find(session[:customer_id]).first
    else
      nil
    end
  end

  def session_present?
    session[:customer_id]
  end
end

front/app/helpers/customers_helper.rb
module CustomersHelper
end

front/app/helpers/dishes_helper.rb
module DishesHelper
end

front/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

front/app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'First Name:' %>
    <%= f.text_field :first_name %>
  </div>
  <div class="form-group">
    <%= f.label 'Last Name:' %>
    <%= f.text_field :last_name %>
  </div>
  <div class="form-group">
    <%= f.label 'Address:' %>
    <%= f.text_field :address %>
  </div>
  <div class="form-group">
    <%= f.label 'Email:' %>
    <%= f.text_field :email %>
  </div>
  <div class="forn-group">
    <%= f.submit class: 'btn btn-primary' %>
    <%#= link_to 'Back', customers_path %>
  </div>
<% end %>

front/app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

front/app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table class="table">
  <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">First Name</th>
        <th scope="col">Last Name</th>
        <th scope="col">Email</th>
        <th scope="col">Address</th>
        <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
        <th scope="row"><%=customer.id%></th>
        <td><%=customer.first_name%></td>
        <td><%=customer.last_name%></td>
        <td><%=customer.email%></td>
        <td><%=customer.address%></td>

        <td><%= link_to 'Log Me In', logmein_path(customer) %></td>

        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

front/app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

front/app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @customer.first_name %> <%= @customer.last_name%></h1>

<p><b>Address: </b><%= @customer.address %></p>
<p><b>Email: </b><%= @customer.email %></p>


<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

front/app/views/dishes/_form.html.erb
<%= form_with(model: dish, url: restaurant_dishes_path, local: true) do |f| %>
  <% if dish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

      <ul>
      <% dish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'Dish Name:' %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label 'Price:' %>
    <%= f.text_field :price %>
  </div>
  <div class="form-group">
    <%= f.label 'Calories:' %>
    <%= f.text_field :calories %>
  </div>

  <div class="forn-group">
    <%= f.submit class: 'btn btn-primary' %>
    <%#= link_to 'Back', restaurants_path %>
  </div>
<% end %>

front/app/views/dishes/edit.html.erb
<h1>Editing Dish</h1>

<%= render 'form', dish: @dish %>

<%= link_to 'Show', restaurant_dish_path(@restaurant, @dish) %> |
<%= link_to 'Back', restaurant_dishes_path %>

front/app/views/dishes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dishes</h1>


<% @dishes.each do |dish| %>
    <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
            <div class="caption">
                <h2><%= dish.name %></h2>
                <p><b>Calories:</b> <%= dish.calories %></p>
                <p><b>Price: $<%= sprintf('%05.2f', dish.price) %></b></p>
                <p><%= link_to 'Show', restaurant_dish_path(@restaurant, dish) %></p>

                <% if session_present? %>
                <h3><%= link_to 'Order', order_path(dish) %></h3>
                <% end %>
            </div>
        </div>
    </div>
<% end %>

<%= link_to 'New Dish', new_restaurant_dish_path %>

front/app/views/dishes/new.html.erb
<h1>New Dish</h1>

<%= render 'form', dish: @dish %>

<%= link_to 'Back', restaurant_dishes_path %>

front/app/views/dishes/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @dish.name %></h1>

<p><b>Price: </b><%= @dish.price %></p>
<p><b>Calories: </b><%= @dish.calories %></p>

<%= link_to 'Back', restaurant_dishes_path %>

front/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Front" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Front</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Restaurants", restaurants_path  %></li>
            <li><%= link_to "Customers", customers_path  %></li>
            <li><%= link_to "Orders", orders_index_path  %></li>
          </ul>
          <span class="navbar-text">
              <b> <%= "Hello, #{current_customer.first_name}!" if session_present? %> </b>
          </span>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>About us</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Agile Team</li>
              <li><%= link_to "Eric Camalionte", "https://www.linkedin.com/in/ecamalionte/"  %></li>
              <li><%= link_to "Gustavo Santana", "https://www.linkedin.com/in/gustavo-santana-a0b11656/"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

front/app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table class="table">
  <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Dish</th>
        <th scope="col">Scheduled</th>
        <th scope="col">Status</th>
        <th scope="col">Quantity</th>
        <th scope="col">Price</th>
        <th scope="col">Total</th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
        <th scope="row"><%=order.id%></th>
        <th scope="row"><%=order.id%></th>
        <td><%=order.deliver_late%></td>
        <td>status</td>
        <td>quantity</td>
        <td>price</td>
        <td>total</td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', root_path %>

front/app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |f| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label 'Restaurant:' %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label 'Contact Name:' %>
    <%= f.text_field :contact_name %>
  </div>
  <div class="form-group">
    <%= f.label 'Contact Phone:' %>
    <%= f.text_field :contact_phone %>
  </div>
  <div class="form-group">
    <%= f.label 'Email:' %>
    <%= f.text_field :email %>
  </div>
  <div class="form-group">
    <%= f.label 'Address:' %>
    <%= f.text_field :address %>
  </div>
  <div class="form-group">
    <%= f.label 'Open At:' %>
    <%= f.text_field :open_at %>
  </div>
  <div class="form-group">
    <%= f.label 'Close At:' %>
    <%= f.text_field :close_at %>
  </div>
  <div class="form-group">
    <%= f.label 'Days of Week:' %>
    <%= f.text_field :days_of_the_week %>
  </div>


  <div class="forn-group">
    <%= f.submit class: 'btn btn-primary' %>
    <%#= link_to 'Back', restaurants_path %>
  </div>
<% end %>

front/app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

front/app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

    <% @restaurants.each do |restaurant| %>
      <div class="col-sm-6 col-md-4">
        <div class="thumbnail">
          <div class="caption">
            <h3><%= restaurant.name %></h3>
            <p><%= restaurant.address %></p>
            <p> <%= link_to 'Dishes', restaurant_dishes_path(restaurant) %> </p>
            <p><%= link_to 'Show', restaurant %></p>
          </div>
        </div>
      </div>
    <% end %>

<%= link_to 'New Restaurant', new_restaurant_path %>

front/app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

front/app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>


<h1><%= @restaurant.name %></h1>

<p><b>Contact Name: </b><%= @restaurant.contact_name %></p>
<p><b>Contact Phone: </b><%= @restaurant.contact_phone %></p>
<p><b>Email: </b><%= @restaurant.email %></p>
<p><b>Address: </b><%= @restaurant.address %></p>


<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>